### ISSUE TITLE
Request Timed Out. Use the "Refresh data" option to try again  Error-ID: a8a396ac

### ISSUE THREAD

**Issue by martinroffler** [Gladior-B-V/google-merchant-center-connector#1]
Dear all

We connected succesfully to our Google merchant center and was able to display all data except "Product total count".
In this form we get the following error:

Request Timed Out. Use the "Refresh data" option to try again

Error-ID: a8a396ac

We have approx 100'000 (soon 500'000) articles maybe the timeout settings are to small to read such big amount of articles.

Could you find a solution to fix this, please?

Many thanks in advance

Martin

**Comment by zoedufrenne** [comment]
Hi @martinroffler ,
Thanks for your message!
We don't have any quotums on the data. But if there are to many articles the connector takes too long and will give a time-out error. Can you share the dashboard with me? because normally when the time-out error is given it's for all the widgets and not just for one. You can send me an email to data-dashboards@gladior.com.

**Comment by zoedufrenne** [comment]
Hi Martin,

Thanks for sharing the dashboard!
Unfortunately you’re right about the ‘too many’ products. It takes the connector too long to get the data from merchant center and that’s why you got the error.  
We’ve added a max. amount of products we can pull without error messages, this amount is set on 1025. More is for our connector not possible. 

We’ve added some extra data fields called; 
Items total
Items valid 

The metric items total will show you the total amount of items you’ve uploaded by the feed. And you can check with ‘items valid’ if the items are valid in Merchant Center. 
We know you can upload items also through other ways, but this is the most used way, that’s why we added it. 

I hope this can replace the total amount of products metric for you!
If you would like an other option, we can help with an extra feauture where we cache the data for you personally. This won't be a free connector, but one especially for you. 

Zoé du Frenne
