### ISSUE TITLE
Issue with PageSpeed Insights Connection with Looker Studio

### ISSUE THREAD

**Issue by Nextgen-Marketing** [Gladior-B-V/google-merchant-center-connector#2]
Hi,

I currently use Looker Studio with the PageSpeeds Insights connection for Clients Monthly SEO/PPC Reports and this connection has stopped working across all of my reports.

When trying to reconnect the connection the error that appears is as below:
```
"Community Connector Error"
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.
Connector details
Unknown Error - There was an error communicating with the service.
Error ID: undefined
```

I have also checked my DataHub account, removed off the connections (just incase the max was reached) re-connected and still the same error.

Can you please advise?

![image](https://user-images.githubusercontent.com/79691905/226899139-6fcb709d-8f27-415e-8bce-e3b701a151d9.png)
![Screenshot 2023-03-22 at 10](https://user-images.githubusercontent.com/79691905/226972053-5bfab32d-f206-45b3-8ed5-a476e9af2d36.png)
![Screenshot 2023-03-22 at 10 33 57](https://user-images.githubusercontent.com/79691905/226899261-83eaf4d7-c9da-479f-8ee6-37c871f09aeb.png)

**Comment by Nextgen-Marketing** [comment]
This looks like it could potentially be an issue with Looker Studio as there are a number of people on Twitter experiencing the same/similar issues

**Comment by daannijkamp** [comment]
@Nextgen-Marketing My bad. It should work again!
