### ISSUE TITLE
Problems with the merchant

### ISSUE THREAD

**Issue by Nicolae1802** [Gladior-B-V/google-merchant-center-connector#3]
Good Morning, we have an ecomerce group that we need to track data down and we have an email that can see all the data in google merchant because with that email we are manager. The problem we have is the connector of google merchant that initially wants the credentials and we put this email but then he needs a "merchant" but didn't find any, so we don't know how to proceed. We need one other email to use? Please it's urgent, thank you in advance.

**Comment by Nicolae1802** [comment]
I know that you are busy, but it's an urgent matter. Thank you!

**Comment by zoedufrenne** [comment]
Hi @Nicolae1802 , Thanks for your message. What exactly do you mean by email? or is this the username you log in to merchant center with? what kind of account is it? Could you show a screenshot? Data you may hide of course.

**Comment by Nicolae1802** [comment]
Hi @zoedufrenne, 
Yes, we use this email to access the data directly on google merchant, but when we enter this email on the box that wants the credentials, in the second step when the connector is telling to choose a merchant, it shows nothing. The question, so, is what kind of error it is or in general how we can proceed? With that email that we are using for google merchant we are standard amministrator. Im sorry but I can’t take a screenshot of this. 

Thank you in advance,
Nicolae

**Comment by zoedufrenne** [comment]
Hi @Nicolae1802 , I'm affraid it's somehting to do with the acces level of the account. I'll check with development about this subject. We have an update planned for the connector, so I hope this will resolve your issue.

**Comment by zoedufrenne** [comment]
Hi @Nicolae1802 can you share your Data Hub ID? You can find it when you are loggedin to the data hub in the right corner on your account and click edit profile. Then the code on the bottom of the pop up is your data hub id. We are gonna track your error id.

**Comment by Nicolae1802** [comment]
Of course @zoedufrenne : google_116408764743670979611

**Comment by Nicolae1802** [comment]
Hello @zoedufrenne , are you the one that have created a facebook ads dashboard on datastudio? Why? We have problem only with the google merchant connector though

**Comment by zoedufrenne** [comment]
Hi @Nicolae1802, We can't create a dashboard under your account.  What is the source? Is it a known source to you? 
We have templates in the Data Hub, but it will only create a dashboard when you create one.

**Comment by zoedufrenne** [comment]
Hi @Nicolae1802 we set a new version live. Can you check if you'll see your other accounts now? :)
