### ISSUE TITLE
CTR is no longer providing data

### ISSUE THREAD

**Issue by VisioConcepts** [Gladior-B-V/google-merchant-center-connector#4]

**Comment by VisioConcepts** [comment]
![Screenshot 2024-04-10 105336](https://github.com/Gladior-B-V/google-merchant-center-connector/assets/165829744/bef43e5a-d4fb-4591-b918-14c09a6f9c97)

**Comment by zoedufrenne** [comment]
Hi @VisioConcepts CTR is working with our dashboards. Can you check the settings or make a new connection? 
![image](https://github.com/Gladior-B-V/google-merchant-center-connector/assets/84766152/483b977d-f318-4e55-951b-15f4f95f6b07)

**Comment by VisioConcepts** [comment]
Thank you for checking into this. Tried reconnecting but unfortunately did not fix the issue. 
Upon checking the settings, Aggregation "Auto" is missing. 

![Screenshot 2024-04-11 102504](https://github.com/Gladior-B-V/google-merchant-center-connector/assets/165829744/d39fa650-fd26-4e92-86bc-93c0e2fdab34)

**Comment by zoedufrenne** [comment]
Hi @VisioConcepts did you first revoke the acces and then reconnect? I can't recreate the issue. There has been an update of the connector 2 weeks ago. This should automatically update the current connectors when you refresh the data fields. But revoke access and then make a new connection with the google merchant center connector, it makes directly a connection to the newest version.

**Comment by VisioConcepts** [comment]
Yes, it seems to have stopped working after that update. I have tried to revoke access, completely deleted all connections, and started a new report, but still had the same issue.

**Comment by zoedufrenne** [comment]
Hi @VisioConcepts can you share your dashboard with me? service@gladior.com, I will check if I can find the reason of the disconnection. Otherwise I can't help you, because the connector is working just fine by our clients.

**Comment by VisioConcepts** [comment]
Sure can, sending now. Thank you.

**Comment by zoedufrenne** [comment]
@VisioConcepts I didn't receive anything. what's the name of the dashboard?

**Comment by VisioConcepts** [comment]
@zoedufrenne Google Merchant Center - Test
https://lookerstudio.google.com/reporting/7c406101-8241-4bf4-86fe-be0b73d559d7

**Comment by VisioConcepts** [comment]
Hi @zoedufrenne , any luck?

**Comment by VisioConcepts** [comment]
Hi @zoedufrenne , just following up here.

**Comment by rkooiker** [comment]
Hi @VisioConcepts, the issue occurs because google merchant center returns incorrect values. You can filter these values by adding a filter in looker studio like: INCLUDE ctr > -1. Personally i would reccomend you to use a calculated field if you know how to, with the function SUM(Clicks) / sum(Impressions), as this gives more accurate results.

**Comment by VisioConcepts** [comment]
@rkooiker Thank you, I appreciate it.
