### ISSUE TITLE
Impressions - Google Merchant Center

### ISSUE THREAD

**Issue by VisioConcepts** [Gladior-B-V/google-merchant-center-connector#5]
Having some data variances:

Merchant Center Impressions:
May 1 - 31,  2024
Real GMC Data: 74.23K Total

Looker Scorecard: 72.93K Total (Small discrepancy.)
Looker Time Series Chart: 19.88K Total (Daily values in the underlying data are incorrect.)

https://lookerstudio.google.com/reporting/7c406101-8241-4bf4-86fe-be0b73d559d7

**Comment by rkooiker** [comment]
Hi @VisioConcepts, you are correct. This is an error in our connector. I will pass this on to our development team, and I will notify you when this is fixed.

**Comment by VisioConcepts** [comment]
Hello @rkooiker , just following up on this for any updates.

**Comment by rkooiker** [comment]
Hi @VisioConcepts, the fix will be released in our next patch. You can expect it before the end of this week.
